-- 0001_initial — the whole metadata store.
--
-- One file, because the store starts empty (feature 006, FR-004): there is no data to
-- carry across and therefore nothing to migrate *from*. Every table here already existed
-- in SQLite; this is a transcription, not a redesign. No new entities, no changed
-- meanings (spec, Key Entities).
--
-- Type mapping (specs/006-postgres-datastore/data-model.md), and the two conservative
-- choices are deliberate:
--   * ISO-8601 timestamps stay `text` (research R5). They are compared lexicographically
--     in both SQL and Python, and for ISO-8601 UTC that order IS chronological order.
--     `timestamptz` would make psycopg return `datetime`, breaking a string slice, every
--     timefmt filter input, ~26 test files, and what renders on the page — in a feature
--     whose first requirement is that nothing user-facing changes (FR-001, SC-007).
--   * 0/1 flags stay integer, as `smallint` (research R6). The app writes `int(...)` and
--     reads `bool(...)`; SQL does `ORDER BY is_leader DESC` and `WHERE grace_used`.
--
-- Both are recorded as deliberate debt: converting is a clean follow-up, and strictly
-- easier after parity is proven than during the engine move.
--
-- `GENERATED BY DEFAULT AS IDENTITY`, not `ALWAYS`: existing tests insert explicit ids
-- and `ALWAYS` rejects that outright (research R7).

-- Migration bookkeeping. `migrate()` also creates this before reading applied versions —
-- it has to, to read them at all — so this is idempotent and exists here only so the file
-- alone fully describes the store for anyone applying it by hand.
CREATE TABLE IF NOT EXISTS schema_migrations (
    version     text PRIMARY KEY,
    applied_at  timestamptz NOT NULL DEFAULT now()
);

-- --- Accounts and league identity -------------------------------------------------

-- The root record. Nearly every other entity references it, which is also what makes it
-- the right row to lock for a per-account credit spend (research R9).
CREATE TABLE users (
    steam_id       text PRIMARY KEY,
    persona_name   text,
    avatar_url     text,
    created_at     text NOT NULL,
    last_login_at  text NOT NULL
);

-- RGL assigns `rgl_team_id`, so it is not an identity column. Same for rgl_seasons.
CREATE TABLE rgl_teams (
    rgl_team_id    integer PRIMARY KEY,
    name           text NOT NULL,
    tag            text,
    format         text NOT NULL,
    division_name  text,
    season_id      integer,
    updated_at     text NOT NULL
);

CREATE TABLE rgl_links (
    steam_id           text PRIMARY KEY REFERENCES users(steam_id),
    profile_name       text,
    state              text NOT NULL,
    is_verified        smallint NOT NULL DEFAULT 0,
    is_banned          smallint NOT NULL DEFAULT 0,
    is_on_probation    smallint NOT NULL DEFAULT 0,
    linked_at          text NOT NULL,
    last_refreshed_at  text NOT NULL
);

CREATE TABLE rgl_memberships (
    steam_id     text NOT NULL REFERENCES users(steam_id),
    rgl_team_id  integer NOT NULL REFERENCES rgl_teams(rgl_team_id),
    PRIMARY KEY (steam_id, rgl_team_id)
);

-- --- Cached league data -----------------------------------------------------------

-- `steam_id` deliberately has NO `REFERENCES users`: a roster lists RGL players, most of
-- whom have never signed in here. An FK would make caching a roster fail.
CREATE TABLE rgl_rosters (
    rgl_team_id  integer NOT NULL REFERENCES rgl_teams(rgl_team_id),
    steam_id     text NOT NULL,
    name         text NOT NULL,
    is_leader    smallint NOT NULL DEFAULT 0,
    PRIMARY KEY (rgl_team_id, steam_id)
);

CREATE TABLE rgl_roster_meta (
    rgl_team_id  integer PRIMARY KEY REFERENCES rgl_teams(rgl_team_id),
    fetched_at   text NOT NULL
);

CREATE TABLE rgl_seasons (
    season_id         integer PRIMARY KEY,
    name              text NOT NULL,
    format            text,
    division_sorting  text NOT NULL DEFAULT '{}',
    fetched_at        text NOT NULL
);

-- `rgl_team_id` deliberately has NO `REFERENCES rgl_teams`: the division browser records
-- which teams are registered in a season *before* hydrating their details, and hydration
-- is bounded per request (RGL_HYDRATE_BATCH). An FK would forbid the very state that makes
-- the browser bounded — and would break the cold-cache path an empty store starts in
-- (FR-007). It stays NOT NULL by virtue of being in the primary key.
CREATE TABLE rgl_season_teams (
    season_id    integer NOT NULL REFERENCES rgl_seasons(season_id),
    rgl_team_id  integer,
    division_id  integer,
    hydrated_at  text,
    PRIMARY KEY (season_id, rgl_team_id)
);

-- --- Scrims -----------------------------------------------------------------------

CREATE TABLE scrims (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    format            text NOT NULL,
    scheduled_at      text NOT NULL,
    origin            text NOT NULL,
    proposer_team_id  integer NOT NULL REFERENCES rgl_teams(rgl_team_id),
    opponent_team_id  integer REFERENCES rgl_teams(rgl_team_id),
    status            text NOT NULL,
    created_by        text NOT NULL REFERENCES users(steam_id),
    created_at        text NOT NULL,
    updated_at        text NOT NULL,
    notes             text
);

-- `player_steam_id` has no FK for the same reason as rgl_rosters.steam_id — attendance is
-- marked for roster players, not only for platform accounts. `marked_by` does have one:
-- whoever marked it necessarily signed in.
CREATE TABLE scrim_attendance (
    scrim_id         integer NOT NULL REFERENCES scrims(id),
    player_steam_id  text NOT NULL,
    player_name      text NOT NULL,
    status           text NOT NULL,
    marked_by        text NOT NULL REFERENCES users(steam_id),
    updated_at       text NOT NULL,
    PRIMARY KEY (scrim_id, player_steam_id)
);

-- --- Payment, credits, servers ----------------------------------------------------

-- A user's own Steam trade URL. Its token is what lets us ask Steam whether a trade from
-- this user would be held, so it is a precondition of paying, not a nicety. Secret-bearing:
-- it must not be exposed in logs or any client-facing surface.
CREATE TABLE steam_trade_links (
    steam_id      text PRIMARY KEY REFERENCES users(steam_id),
    trade_url     text NOT NULL,
    partner_id    text NOT NULL,
    access_token  text NOT NULL,
    updated_at    text NOT NULL
);

-- One attempt to pay, by any method. `method` is what keeps the model open to payment
-- methods beyond Steam trades without reworking entitlement.
--
-- UNIQUE (method, provider_ref) is the exactly-once guarantee for crediting (FR-009). The
-- poller re-reads the same offers on every run and can be run twice by hand, so idempotency
-- cannot rest on it behaving well — the store enforces it. Both engines treat NULL as
-- non-colliding here, which is what lets many `provider_ref IS NULL` rows coexist while
-- claimed offers stay unique.
CREATE TABLE payments (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    steam_id         text NOT NULL REFERENCES users(steam_id),
    method           text NOT NULL,
    provider_ref     text,
    state            text NOT NULL,
    state_reason     text,
    items_expected   integer NOT NULL,
    items_received   integer,
    credits_granted  integer,
    hold_until       text,
    target_scrim_id  integer REFERENCES scrims(id),
    created_at       text NOT NULL,
    updated_at       text NOT NULL,
    UNIQUE (method, provider_ref)
);

-- A server a team is entitled to.
--
-- The RCON/administrative password is deliberately absent and MUST NOT be added:
-- constitution IV forbids storing it beside a server's joinable details or delivering it to
-- any client. The absence is load-bearing, and it would survive an engine change unexamined
-- unless somebody said so — so this says so. It also means no backup of this store can
-- contain it.
CREATE TABLE servers (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scrim_id          integer REFERENCES scrims(id),
    owner_steam_id    text NOT NULL REFERENCES users(steam_id),
    team_id           integer REFERENCES rgl_teams(rgl_team_id),
    state             text NOT NULL,
    name              text NOT NULL,
    map               text NOT NULL,
    max_slots         integer NOT NULL,
    join_password     text,
    address           text,
    players           integer,
    window_starts_at  text,
    window_ends_at    text,
    -- Season-term servers only (scrim_id IS NULL). Display-only for now: the constitution
    -- settles the per-scrim credit but leaves the season-term purchase unit undefined, so
    -- nothing can create one of these yet.
    term_ends_at      text,
    grace_used        smallint NOT NULL DEFAULT 0,
    demo              smallint NOT NULL DEFAULT 0,
    stopped_reason    text,
    created_at        text NOT NULL,
    updated_at        text NOT NULL
);

-- At most one server per scrim (FR-010). A partial unique index, now genuinely enforced
-- under concurrency rather than under a global write lock.
CREATE UNIQUE INDEX idx_servers_scrim ON servers(scrim_id)
    WHERE scrim_id IS NOT NULL;

-- Append-only. No UPDATE, no DELETE, ever. The single source of truth for every balance:
-- available credits are SUM(delta), never a cached column that could disagree with these
-- rows and leave the ledger untrustworthy for exactly the dispute it exists to settle
-- (FR-013, constitution VIII).
CREATE TABLE credit_ledger (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    steam_id    text NOT NULL REFERENCES users(steam_id),
    delta       integer NOT NULL,
    kind        text NOT NULL,
    cause       text NOT NULL,
    payment_id  integer REFERENCES payments(id),
    scrim_id    integer REFERENCES scrims(id),
    server_id   integer REFERENCES servers(id),
    created_at  text NOT NULL
);

-- Keeps SUM(delta) cheap as the ledger grows, and it is the index the per-account row lock
-- for a credit spend rides alongside (research R9).
CREATE INDEX idx_credit_ledger_steam_id ON credit_ledger(steam_id);
